#!/usr/bin/env sh
#
# Git Commit Message Hook
#
# A local git hook that runs after a commit message is entered, recieving the
# file containing the commit message as its only argument.

# Executes the husky shell script.
. "$(dirname -- "$0")/_/husky.sh"

# Runs commitlint against the file containing the commit message. The `--edit`
# flag tells commitlint to fallback to `COMMIT_EDITMSG` in the .git folder if no
# file is passed to the positional argument.
npx commitlint --verbose --edit ${1}
